sudo: required
services:
    - docker

before_install:
    - docker build -t hhermas/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run hhermas/react-test npm test -- --coverage

after_success:
    - docker build -t hhermas/multi-client ./client
    - docker build -t hhermas/multi-nginx ./nginx
    - docker build -t hhermas/multi-server ./server
    - docker build -t hhermas/multi-worker ./worker

    #Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    #push to docker hub
    - docker push hhermas/multi-client
    - docker push hhermas/multi-nginx
    - docker push hhermas/multi-server
    - docker push hhermas/multi-worker

    

