sudo: required
services:
    - docker

before_install:
    - docker build -t hhermas/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true hhermas/react-test npm test -- --coverage

after_success:
    - docker build -t hhermas/multi-client ./client
    - docker build -t hhermas/multi-nginx ./nginx
    - docker build -t hhermas/multi-server ./server
    - docker build -t hhermas/multi-worker ./worker

    #Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    #push to docker hub
    - docker push hhermas/multi-client
    - docker push hhermas/multi-nginx
    - docker push hhermas/multi-server
    - docker push hhermas/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-433637443327
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY



    

